# Generated by Django 3.1.5 on 2021-01-10 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=200)),
                ('Name', models.CharField(max_length=200)),
                ('Birthday', models.DateTimeField()),
                ('Address', models.CharField(max_length=200)),
                ('Telephone', models.CharField(max_length=11)),
                ('Created', models.DateTimeField()),
                ('Modified', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=200)),
                ('Created', models.DateTimeField()),
                ('Modified', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.author')),
            ],
        ),
    ]
